sudo: false
dist: trusty
language: python
env:
    - PYTHONASYNCIODEBUG=1
python:
    - '3.5'
    - '3.6'
    - '3.7-dev'
install:
    - pip install pipenv
    - pushd src/ui_pkg/
    - pipenv install --dev
    - popd
script:
    - pipenv run flake8 --ignore=E501 src
    - pushd src/ui_pkg/
    - pipenv run nose2 --with-coverage
    - popd
after_success:
    - coveralls
