sudo: false
dist: trusty
language: python
env:
    - PYTHONASYNCIODEBUG=1
python:
    - '3.5'
    - '3.6'
    - '3.7-dev'
install:
    - pip install pipenv
    - pipenv install --dev
script:
    - pipenv run flake8 src/httptemplate
    - pipenv run nose2 --with-coverage
after_success:
    - coveralls
